### ISSUE TITLE
Please Add BrainBlocks

### ISSUE THREAD

**Issue by schenkty** [RaiMakers/awesome-raiblocks#12]
Hey, 

If possible, please add brainblocks. We have the following
[iOS client app](https://github.com/brainblocks/brainblocks-ios)
[iOS SDK](https://github.com/brainblocks/brainblocks-ios-sdk)
[woocommerce client](https://github.com/brainblocks/woocommerce-brainblocks)
[js client](https://github.com/brainblocks/brainblocks)

Thanks

**Comment by vardthomas** [comment]
Added, thanks!
